spring:
  application:
    name: backend
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 900 # 15 mins
    refreshTokenExpiration : 604800 # 7 days
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}