spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/bookfair?createDatabaseIfNotExist=true
    username: postgres
    password: ""
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
