spring:
  app:
    frontend-url: http://localhost:5173
  datasource:
    url: jdbc:postgresql://localhost:5432/bookfair
    username: postgres
    password: "000000"
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true