spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookfair
    username: postgres
    password: "1234"
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: avishka2003ishan2003@gmail.com
    password: "juhf oyef cxti iqlr"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 300000 # 5 mins
    refreshTokenExpiration : 604800 # 7 days